"""Constants used in other files"""
DATA_WORLDS = [
    "Adamantoise",
    "Aegis",
    "Alexander",
    "Anima",
    "Asura",
    "Atomos",
    "Bahamut",
    "Balmung",
    "Behemoth",
    "Belias",
    "Brynhildr",
    "Cactuar",
    "Carbuncle",
    "Cerberus",
    "Chocobo",
    "Coeurl",
    "Diabolos",
    "Durandal",
    "Excalibur",
    "Exodus",
    "Faerie",
    "Famfrit",
    "Fenrir",
    "Garuda",
    "Gilgamesh",
    "Goblin",
    "Gungnir",
    "Hades",
    "Hyperion",
    "Ifrit",
    "Ixion",
    "Jenova",
    "Kujata",
    "Lamia",
    "Leviathan",
    "Lich",
    "Louisoix",
    "Malboro",
    "Mandragora",
    "Masamune",
    "Mateus",
    "Midgardsormr",
    "Moogle",
    "Odin",
    "Omega",
    "Pandaemonium",
    "Phoenix",
    "Ragnarok",
    "Ramuh",
    "Ridill",
    "Sargatanas",
    "Shinryu",
    "Shiva",
    "Siren",
    "Tiamat",
    "Titan",
    "Tonberry",
    "Typhon",
    "Ultima",
    "Ultros",
    "Unicorn",
    "Valefor",
    "Yojimbo",
    "Zalera",
    "Zeromus",
    "Zodiark",
    "Spriggan",
    "Twintania",
    "HongYuHai",
    "ShenYiZhiDi",
    "LaNuoXiYa",
    "HuanYingQunDao",
    "MengYaChi",
    "YuZhouHeYin",
    "WoXianXiRan",
    "ChenXiWangZuo",
    "BaiYinXiang",
    "BaiJinHuanXiang",
    "ShenQuanHen",
    "ChaoFengTing",
    "LvRenZhanQiao",
    "FuXiaoZhiJian",
    "Longchaoshendian",
    "MengYuBaoJing",
    "ZiShuiZhanQiao",
    "YanXia",
    "JingYuZhuangYuan",
    "MoDuNa",
    "HaiMaoChaWu",
    "RouFengHaiWan",
    "HuPoYuan",
]

CHAR_CLASS_NAMES = {
    1: ["gladiator", "paladin"],
    2: ["pugilist", "monk"],
    3: ["marauder", "warrior"],
    4: ["lancer", "dragoon"],
    5: ["archer", "bard"],
    6: ["conjurer", "white mage"],
    7: ["thaumaturge", "black mage"],
    8: ["carpenter"],
    9: ["blacksmith"],
    10: ["armorer"],
    11: ["goldsmith"],
    12: ["leatherworker"],
    13: ["weaver"],
    14: ["alchemist"],
    15: ["culinarian"],
    16: ["miner"],
    17: ["botanist"],
    18: ["fisher"],
    26: ["arcanist", "summoner"],
    28: ["arcanist", "scholar"],
    29: ["rogue", "ninja"],
    31: ["machinist"],
    32: ["dark knight"],
    33: ["astrologian"],
    34: ["samurai"],
    35: ["red mage"],
    36: ["blue mage"],
    37: ["gunbreaker"],
    38: ["dancer"],
    39: ["reaper"],
    40: ["sage"],
}

TEMP_CHAR_CLASS_NAMES = {
    1: "gladiator",
    2: "pugilist",
    3: "marauder",
    4: "lancer",
    5: "archer",
    6: "conjurer",
    7: "thaumaturge",
    8: "carpenter",
    9: "blacksmith",
    10: "armorer",
    11: "goldsmith",
    12: "leatherworker",
    13: "weaver",
    14: "alchemist",
    15: "culinarian",
    16: "miner",
    17: "botanist",
    18: "fisher",
    19: "paladin",
    20: "monk",
    21: "warrior",
    22: "dragoon",
    23: "bard",
    24: "white mage",
    25: "black mage",
    26: "arcanist",
    27: "summoner",
    28: "scholar",
    29: "rogue",
    30: "ninja",
    31: "machinist",
    32: "dark knight",
    33: "astrologian",
    34: "samurai",
    35: "red mage",
    36: "blue mage",
    37: "gunbreaker",
    38: "dancer",
    39: "reaper",
    40: "sage",
}

CHAR_LODESTONE_URL = "https://eu.finalfantasyxiv.com/lodestone/character/"

CHAR_CLASS_TYPE_MELEE_DPS = (2, 4, 20, 22, 29, 30, 34, 39)
CHAR_CLASS_TYPE_RANGE_PHY_DPS = (5, 23, 31, 38)
CHAR_CLASS_TYPE_RANGE_MAG_DPS = (7, 25, 26, 27, 35, 36)
CHAR_CLASS_TYPE_TANK = (1, 3, 19, 21, 32, 37)
CHAR_CLASS_TYPE_HEALER = (6, 24, 28, 33, 40)

CHAR_CLASS_CRAFTER = (8, 9, 10, 11, 12, 13, 14, 15)
CHAR_CLASS_GATHERER = (16, 17, 18)


GRAND_COMP_HEX_COLORS = (
    0xB41B1E,
    0xDAAB16,
    0x213443,
)  # ("Maelstrom", "Twin Adder" ,"Immortal Flames")
